name: device_preview
version: 0.2.7
description: Approximate how your app looks and performs on another device.
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  http: ^0.12.0
  flutter_svg: ^0.14.3
  flutter: 
    sdk: flutter 
  meta: ^1.1.8
  http: ^0.14.0
  path_provider: ^1.6.1
  path_provider_macos: ^0.0.3+1

  # This is a temporary hack to enable Windows to work. It is not recommended
  # since this package may change at any time in ways that break. 
  path_provider_fde:
    git:
      url: https://github.com/google/flutter-desktop-embedding/
      path: plugins/flutter_plugins/path_provider_fde
 
dev_dependencies:
  flutter_test:
    sdk: flutter 
  pedantic: ^1.9.0